### ISSUE TITLE
Error: Cannot find module 'lodash._baseclone'

### ISSUE THREAD

**Issue by theskillwithin** [RoccoC/webpack-build-notifier#15] opened 2017-06-18 23:27 UTC
help can't seem to figure out this issue
```
➜  v2 git:(blue/service-fulfillment-file-uploader) npm run webpack --progress --watch --config webpack.config.babel.js
npm ERR! missing script: webpack

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aupeterson/.npm/_logs/2017-06-18T23_24_20_207Z-debug.log
➜  v2 git:(blue/service-fulfillment-file-uploader) webpack --progress --watch --config webpack.config.babel.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'lodash._baseclone'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aupeterson/Projects/ansible-playbooks/marketplace/git-repos/marketplace/Apps/v2/node_modules/webpack-build-notifier/node_modules/lodash.clonedeep/index.js:9:17)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/aupeterson/Projects/ansible-playbooks/marketplace/git-repos/marketplace/Apps/v2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by RoccoC** [comment] 2017-06-22 22:16
@theskillwithin , I wasn't able to reproduce this issue. What version of node/npm are you using? Win or Mac OS?

**Comment by RoccoC** [comment] 2017-07-11 14:23
Closing this as I was unable to reproduce on Windows or Mac OS. Please re-open with details on a reproduce case and I will investigate. Thanks!

**Closed by RoccoC** 2017-07-11 14:23 UTC
